# Pandas Approach

In [76]:
import pandas as pd
import os
import openpyxl as opl
import numpy as np

# Energy data processing

In [77]:
energy = pd.read_excel("Energy Indicators.xls")

# dropping extra columns
energy.drop(columns = ["Unnamed: 0", "Unnamed: 2"], axis = 1, inplace = True)
energy = energy[~energy["Unnamed: 1"].isna()]
energy = energy[~energy["Unnamed: 4"].isna()]

# column names
column_list = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewabl\'s']

#rename columns
energy.columns =  column_list

# removing string values and coercing errors
energy['Energy Supply'] = pd.to_numeric(energy['Energy Supply'], errors='coerce')
energy['Energy Supply per Capita'] = pd.to_numeric(energy['Energy Supply per Capita'], errors='coerce')


# changing Energy unit from petajoules to gigajoules
energy['Energy Supply'] = energy['Energy Supply']*1000000
energy['Energy Supply per Capita'] = energy['Energy Supply per Capita']*1000000

In [78]:
# Renaming Countries(allows manipulating the entries in a single place)
country_name_dict_energy = {"Republic of Korea": "South Korea", 
                    "United States of America": "United States", 
                    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", 
                    "China, Hong Kong Special Administrative Region": "Hong Kong"
}

energy = energy.replace({'Country':country_name_dict_energy})

In [79]:
# Remove parantheses from the Country names
energy['Country'] = energy['Country'].str.replace(r"\(.*\)","", regex=True)

In [80]:
display(energy.head(50))

,Country,Energy Supply,Energy Supply per Capita,% Renewabl's
17,Afghanistan,3.210000e+08,10000000.0,78.66928
18,Albania,1.020000e+08,35000000.0,100
19,Algeria,1.959000e+09,51000000.0,0.55101
20,American Samoa,NaN,NaN,0.641026
21,Andorra,9.000000e+06,121000000.0,88.69565
22,Angola,6.420000e+08,27000000.0,70.90909
23,Anguilla,2.000000e+06,136000000.0,0
24,Antigua and Barbuda,8.000000e+06,84000000.0,0
25,Argentina,3.378000e+09,79000000.0,24.06452
26,Armenia,1.430000e+08,48000000.0,28.23606
27,Aruba,1.200000e+07,120000000.0,14.87069
28,Australia,5.386000e+09,231000000.0,11.81081
29,Austria,1.391000e+09,164000000.0,72.45282
30,Azerbaijan,5.670000e+08,60000000.0,6.384345
31,Bahamas,4.500000e+07,118000000.0,0
32,Bahrain,5.740000e+08,425000000.0,0
33,Bangladesh,1.625000e+09,10000000.0,1.966329
34,Barbados,1.900000e+07,69000000.0,0
35,Belarus,1.142000e+09,120000000.0,0.463389
36,Belgium,2.338000e+09,210000000.0,9.959739
37,Belize,1.300000e+07,39000000.0,64.69003
38,Benin,1.700000e+08,16000000.0,0
39,Bermuda,6.000000e+06,88000000.0,0
40,Bhutan,6.300000e+07,83000000.0,100
41,Bolivia,3.360000e+08,32000000.0,31.47712
42,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213000000.0,0
43,Bosnia and Herzegovina,2.660000e+08,70000000.0,41.46467
44,Botswana,8.600000e+07,39000000.0,0.131406
45,Brazil,1.214900e+10,59000000.0,69.64803
46,British Virgin Islands,2.000000e+06,85000000.0,0
47,Brunei Darussalam,1.270000e+08,310000000.0,0.045434
48,Bulgaria,7.030000e+08,97000000.0,17.23461
49,Burkina Faso,1.640000e+08,10000000.0,14.50068
50,Burundi,5.800000e+07,6000000.0,86.79245
51,Cabo Verde,7.000000e+06,15000000.0,21.22762
52,Cambodia,2.500000e+08,17000000.0,57.31159
53,Cameroon,3.070000e+08,14000000.0,70.88626
54,Canada,1.043100e+10,296000000.0,61.94543
55,Cayman Islands,8.000000e+06,131000000.0,0
56,Central African Republic,2.300000e+07,5000000.0,85.63536
57,Chad,7.700000e+07,6000000.0,0
58,Chile,1.613000e+09,92000000.0,28.00657
59,China,1.271910e+11,93000000.0,19.75491
60,Hong Kong,5.850000e+08,82000000.0,0
61,"China, Macao Special Administrative Region",4.700000e+07,83000000.0,0
62,Colombia,1.513000e+09,32000000.0,63.00284
63,Comoros,5.000000e+06,7000000.0,11.62791
64,Congo,1.020000e+08,23000000.0,57.74887
65,Cook Islands,1.000000e+06,48000000.0,0
66,Costa Rica,2.220000e+08,47000000.0,88.73642

In [81]:
#stripping leading and trailing spaces
energy['Country'] = energy['Country'].str.strip()

# GDP data Processing

In [82]:
#Reading the gdp data
gdp = pd.read_csv("GDP.csv")

#Removing header
gdp = gdp.iloc[3:]

#Renaming Columns
gdp.columns = gdp.iloc[0]
gdp = gdp.iloc[1:]
gdp['Country'] = gdp['Country Name']

In [83]:
# Renaming Countries(allows manipulating the entries in a single place)
country_name_dict_gdp = {"Korea, Rep.": "South Korea",  
                    "Iran, Islamic Rep.": "Iran", 
                    "Hong Kong SAR, China": "Hong Kong" 
}

gdp = gdp.replace({'Country':country_name_dict_gdp})

In [84]:
# Extracting the required year columns
column_list_gdp = [*range(2006, 2016, 1)]
column_list_gdp.append('Country')
gdp = gdp[column_list_gdp]

In [85]:
display(gdp.head(10))

3,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Country
4,2.469832e+09,2.677654e+09,2.843017e+09,2.553631e+09,2.453631e+09,2.637989e+09,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,Aruba
5,5.759210e+11,6.611790e+11,7.082870e+11,7.192170e+11,8.604780e+11,9.644180e+11,9.730430e+11,9.839370e+11,1.003680e+12,9.242530e+11,Africa Eastern and Southern
6,6.971286e+09,9.747880e+09,1.010931e+10,1.241616e+10,1.585668e+10,1.780511e+10,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,Afghanistan
7,3.933050e+11,4.617910e+11,5.664810e+11,5.070440e+11,5.915960e+11,6.709830e+11,7.275700e+11,8.207930e+11,8.649900e+11,7.607340e+11,Africa Western and Central
8,5.238101e+10,6.526645e+10,8.853861e+10,7.030717e+10,8.169956e+10,1.094370e+11,1.249980e+11,1.334020e+11,1.372440e+11,8.721929e+10,Angola
9,8.896073e+09,1.067732e+10,1.288135e+10,1.204421e+10,1.192692e+10,1.289076e+10,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,Albania
10,3.456442e+09,3.952601e+09,4.085631e+09,3.674410e+09,3.449926e+09,3.629134e+09,3.188653e+09,3.193513e+09,3.271686e+09,2.789881e+09,Andorra
11,1.538300e+12,1.790040e+12,2.253740e+12,1.978810e+12,2.327010e+12,2.547960e+12,2.778080e+12,2.834610e+12,2.876010e+12,2.518700e+12,Arab World
12,2.221170e+11,2.579160e+11,3.154750e+11,2.535470e+11,2.897870e+11,3.506660e+11,3.745910e+11,3.901080e+11,4.031370e+11,3.581350e+11,United Arab Emirates
13,2.325570e+11,2.875310e+11,3.615580e+11,3.329760e+11,4.236270e+11,5.301630e+11,5.459820e+11,5.520250e+11,5.263200e+11,5.947490e+11,Argentina

In [86]:
#stripping leading and trailing spaces
gdp['Country'] = gdp['Country'].str.strip()

# ScimEn Data Processing

In [87]:
#Reading the scimen data and filetering for top 15 countries
scimenrank = pd.read_excel("scimagojr country rank 1996-2021.xlsx")

#Filtering data for top fifteen countries
scimenrank['Rank'] = pd.to_numeric(scimenrank['Rank'])
scimenrank = scimenrank[scimenrank['Rank'] <= 15]

#filtering unrequired columns
scimenrank.drop(columns = ['Rank', 'Region'], axis = 1, inplace = True)

In [88]:
display(scimenrank)

,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,China,303064,301778,3036531,2092737,10.02,273
1,United States,184851,181106,2623922,819242,14.19,389
2,India,60257,58589,590570,213760,9.80,198
3,Japan,52780,52281,557023,132113,10.55,203
4,United Kingdom,47141,45928,748994,132737,15.89,244
5,Germany,42343,41464,528645,115432,12.48,211
6,Russian Federation,39424,39189,142937,67935,3.63,96
7,Canada,35588,34940,665415,113363,18.70,246
8,Italy,31260,29959,433388,105641,13.86,177
9,South Korea,31200,30949,405923,74753,13.01,169
10,France,26848,26320,403834,73792,15.04,190
11,Iran,25481,25204,398571,122647,15.64,159
12,Spain,24969,24505,427391,77583,17.12,187
13,Brazil,23110,22762,219895,53635,9.52,139
14,Australia,22803,22276,396186,62694,17.37,192

# Merging data to form results

In [89]:
# Merging dataframes energy and gdp
result = energy.merge(gdp, how = 'left', on = 'Country')

# Merging dataframes result and ScimEn data
result = scimenrank.merge(result, how = 'left', on = 'Country')

In [90]:
display(result)

,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewabl's,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
0,China,303064,301778,3036531,2092737,10.02,273,1.271910e+11,93000000.0,19.75491,2.752130e+12,3.550340e+12,4.594310e+12,5.101700e+12,6.087160e+12,7.551500e+12,8.532230e+12,9.570410e+12,1.047570e+13,1.106160e+13
1,United States,184851,181106,2623922,819242,14.19,389,9.083800e+10,286000000.0,11.57098,1.381560e+13,1.447420e+13,1.476990e+13,1.447810e+13,1.504900e+13,1.559970e+13,1.625400e+13,1.684320e+13,1.755070e+13,1.820600e+13
2,India,60257,58589,590570,213760,9.80,198,3.319500e+10,26000000.0,14.96908,9.402600e+11,1.216740e+12,1.198900e+12,1.341890e+12,1.675620e+12,1.823050e+12,1.827640e+12,1.856720e+12,2.039130e+12,2.103590e+12
3,Japan,52780,52281,557023,132113,10.55,203,1.898400e+10,149000000.0,10.23282,4.601660e+12,4.579750e+12,5.106680e+12,5.289490e+12,5.759070e+12,6.233150e+12,6.272360e+12,5.212330e+12,4.896990e+12,4.444930e+12
4,United Kingdom,47141,45928,748994,132737,15.89,244,7.920000e+09,124000000.0,10.60047,2.717060e+12,3.106180e+12,2.938880e+12,2.425800e+12,2.491110e+12,2.674890e+12,2.719160e+12,2.803290e+12,3.087170e+12,2.956570e+12
5,Germany,42343,41464,528645,115432,12.48,211,1.326100e+10,165000000.0,17.90153,2.994700e+12,3.425580e+12,3.745260e+12,3.411260e+12,3.399670e+12,3.749310e+12,3.527140e+12,3.733800e+12,3.889090e+12,3.357590e+12
6,Russian Federation,39424,39189,142937,67935,3.63,96,3.070900e+10,214000000.0,17.28868,9.899310e+11,1.299710e+12,1.660850e+12,1.222640e+12,1.524920e+12,2.045930e+12,2.208300e+12,2.292470e+12,2.059240e+12,1.363480e+12
7,Canada,35588,34940,665415,113363,18.70,246,1.043100e+10,296000000.0,61.94543,1.319260e+12,1.468820e+12,1.552990e+12,1.374630e+12,1.617340e+12,1.793330e+12,1.828370e+12,1.846600e+12,1.805750e+12,1.556510e+12
8,Italy,31260,29959,433388,105641,13.86,177,6.530000e+09,109000000.0,33.66723,1.949550e+12,2.213100e+12,2.408660e+12,2.199930e+12,2.136100e+12,2.294990e+12,2.086960e+12,2.141920e+12,2.162010e+12,1.836640e+12
9,South Korea,31200,30949,405923,74753,13.01,169,1.100700e+10,221000000.0,2.279353,1.053220e+12,1.172610e+12,1.047340e+12,9.439420e+11,1.144070e+12,1.253220e+12,1.278430e+12,1.370800e+12,1.484320e+12,1.465770e+12
10,France,26848,26320,403834,73792,15.04,190,1.059700e+10,166000000.0,17.02028,2.320540e+12,2.660590e+12,2.930300e+12,2.700890e+12,2.645190e+12,2.865160e+12,2.683670e+12,2.811880e+12,2.855960e+12,2.439190e+12
11,Iran,25481,25204,398571,122647,15.64,159,9.172000e+09,119000000.0,5.707721,2.662990e+11,3.498820e+11,4.123360e+11,4.163970e+11,4.868080e+11,6.261330e+11,6.440360e+11,4.927760e+11,4.603830e+11,4.082130e+11
12,Spain,24969,24505,427391,77583,17.12,187,4.923000e+09,106000000.0,37.96859,1.260400e+12,1.474000e+12,1.631860e+12,1.491470e+12,1.422110e+12,1.480710e+12,1.324740e+12,1.355140e+12,1.371220e+12,1.195600e+12
13,Brazil,23110,22762,219895,53635,9.52,139,1.214900e+10,59000000.0,69.64803,1.107630e+12,1.397110e+12,1.695860e+12,1.667000e+12,2.208840e+12,2.616160e+12,2.465230e+12,2.472820e+12,2.456040e+12,1.802210e+12
14,Australia,22803,22276,396186,62694,17.37,192,5.386000e+09,231000000.0,11.81081,7.475560e+11,8.539550e+11,1.055130e+12,9.280430e+11,1.147590e+12,1.397910e+12,1.546510e+12,1.576340e+12,1.467500e+12,1.350530e+12

In [91]:
result.shape

(15, 20)

In [92]:
result.to_csv('result.csv', index=False)
result.to_excel('result.xlsx', index=False)